CC=	newcc
CFLAGS=	-O
OFILES= asin.o atan.o besj0.o besj1.o besjn.o erf.o exp.o fabs.o floor.o \
	fmod.o gamma.o hypot.o log.o pow.o pow10.o sin.o sinh.o sqrt.o \
	tan.o tanh.o

all: $(OFILES)

install: $(OFILES)
	mv $(OFILES) ../OBJ
