# This makefile is created automagically by ../Makefile
FC=../compiler/fc
all: \
6x10.snf \
6x12.snf \
6x13.snf \
8x13.snf \
8x13bold.snf \
9x15.snf \
apl-s25.snf \
arrow3.snf \
chp-s25.snf \
chs-s50.snf \
crturz.snf \
cursor.snf \
cyr-s25.snf \
cyr-s30.snf \
cyr-s38.snf \
dancer.snf \
ent.snf \
fcor-20.snf \
fg-13.snf \
fg-16.snf \
fg-18.snf \
fg-20.snf \
fg-22.snf \
fg-25.snf \
fg-30.snf \
fg-40.snf \
fg1-25.snf \
fgb-13.snf \
fgb-25.snf \
fgb1-25.snf \
fgb1-30.snf \
fgi-20.snf \
fgi1-25.snf \
fgs-22.snf \
fixed.snf \
fqxb-25.snf \
fr-25.snf \
fr-33.snf \
fr1-25.snf \
fr2-25.snf \
fr3-25.snf \
frb-32.snf \
fri-33.snf \
fri1-25.snf \
ger-s35.snf \
grk-s25.snf \
grk-s30.snf \
hbr-s25.snf \
hbr-s40.snf \
ipa-s25.snf \
krivo.snf \
lat-s30.snf \
met25.snf \
micro.snf \
mit.snf \
oldera.snf \
plunk.snf \
rot-s16.snf \
runlen.snf \
sans12.snf \
sansb12.snf \
sansi12.snf \
serif10.snf \
serif12.snf \
serifb10.snf \
serifb12.snf \
serifi10.snf \
serifi12.snf \
stan.snf \
stempl.snf \
sub.snf \
subsub.snf \
sup.snf \
supsup.snf \
swd-s30.snf \
sym-s25.snf \
sym-s53.snf \
variable.snf \
vbee-36.snf \
vctl-25.snf \
vg-13.snf \
vg-20.snf \
vg-25.snf \
vg-31.snf \
vg-40.snf \
vgb-25.snf \
vgb-31.snf \
vgbc-25.snf \
vgh-25.snf \
vgi-20.snf \
vgi-25.snf \
vgi-31.snf \
vgl-40.snf \
vgvb-31.snf \
vmic-25.snf \
vply-36.snf \
vr-20.snf \
vr-25.snf \
vr-27.snf \
vr-30.snf \
vr-31.snf \
vr-40.snf \
vrb-25.snf \
vrb-30.snf \
vrb-31.snf \
vrb-35.snf \
vrb-37.snf \
vri-25.snf \
vri-30.snf \
vri-31.snf \
vri-40.snf \
vsg-114.snf \
vsgn-57.snf \
vshd-40.snf \
vtbold.snf \
vtsingle.snf \
vxms-37.snf \
vxms-43.snf \
xif-s25.snf

6x10.snf: ../bdf/6x10.bdf $(FC)
	$(FC) ../bdf/6x10.bdf >$@
6x12.snf: ../bdf/6x12.bdf $(FC)
	$(FC) ../bdf/6x12.bdf >$@
6x13.snf: ../bdf/6x13.bdf $(FC)
	$(FC) ../bdf/6x13.bdf >$@
8x13.snf: ../bdf/8x13.bdf $(FC)
	$(FC) ../bdf/8x13.bdf >$@
8x13bold.snf: ../bdf/8x13bold.bdf $(FC)
	$(FC) ../bdf/8x13bold.bdf >$@
9x15.snf: ../bdf/9x15.bdf $(FC)
	$(FC) ../bdf/9x15.bdf >$@
apl-s25.snf: ../bdf/apl-s25.bdf $(FC)
	$(FC) ../bdf/apl-s25.bdf >$@
arrow3.snf: ../bdf/arrow3.bdf $(FC)
	$(FC) ../bdf/arrow3.bdf >$@
chp-s25.snf: ../bdf/chp-s25.bdf $(FC)
	$(FC) ../bdf/chp-s25.bdf >$@
chs-s50.snf: ../bdf/chs-s50.bdf $(FC)
	$(FC) ../bdf/chs-s50.bdf >$@
crturz.snf: ../bdf/crturz.bdf $(FC)
	$(FC) ../bdf/crturz.bdf >$@
cursor.snf: ../bdf/cursor.bdf $(FC)
	$(FC) ../bdf/cursor.bdf >$@
cyr-s25.snf: ../bdf/cyr-s25.bdf $(FC)
	$(FC) ../bdf/cyr-s25.bdf >$@
cyr-s30.snf: ../bdf/cyr-s30.bdf $(FC)
	$(FC) ../bdf/cyr-s30.bdf >$@
cyr-s38.snf: ../bdf/cyr-s38.bdf $(FC)
	$(FC) ../bdf/cyr-s38.bdf >$@
dancer.snf: ../bdf/dancer.bdf $(FC)
	$(FC) ../bdf/dancer.bdf >$@
ent.snf: ../bdf/ent.bdf $(FC)
	$(FC) ../bdf/ent.bdf >$@
fcor-20.snf: ../bdf/fcor-20.bdf $(FC)
	$(FC) ../bdf/fcor-20.bdf >$@
fg-13.snf: ../bdf/fg-13.bdf $(FC)
	$(FC) ../bdf/fg-13.bdf >$@
fg-16.snf: ../bdf/fg-16.bdf $(FC)
	$(FC) ../bdf/fg-16.bdf >$@
fg-18.snf: ../bdf/fg-18.bdf $(FC)
	$(FC) ../bdf/fg-18.bdf >$@
fg-20.snf: ../bdf/fg-20.bdf $(FC)
	$(FC) ../bdf/fg-20.bdf >$@
fg-22.snf: ../bdf/fg-22.bdf $(FC)
	$(FC) ../bdf/fg-22.bdf >$@
fg-25.snf: ../bdf/fg-25.bdf $(FC)
	$(FC) ../bdf/fg-25.bdf >$@
fg-30.snf: ../bdf/fg-30.bdf $(FC)
	$(FC) ../bdf/fg-30.bdf >$@
fg-40.snf: ../bdf/fg-40.bdf $(FC)
	$(FC) ../bdf/fg-40.bdf >$@
fg1-25.snf: ../bdf/fg1-25.bdf $(FC)
	$(FC) ../bdf/fg1-25.bdf >$@
fgb-13.snf: ../bdf/fgb-13.bdf $(FC)
	$(FC) ../bdf/fgb-13.bdf >$@
fgb-25.snf: ../bdf/fgb-25.bdf $(FC)
	$(FC) ../bdf/fgb-25.bdf >$@
fgb1-25.snf: ../bdf/fgb1-25.bdf $(FC)
	$(FC) ../bdf/fgb1-25.bdf >$@
fgb1-30.snf: ../bdf/fgb1-30.bdf $(FC)
	$(FC) ../bdf/fgb1-30.bdf >$@
fgi-20.snf: ../bdf/fgi-20.bdf $(FC)
	$(FC) ../bdf/fgi-20.bdf >$@
fgi1-25.snf: ../bdf/fgi1-25.bdf $(FC)
	$(FC) ../bdf/fgi1-25.bdf >$@
fgs-22.snf: ../bdf/fgs-22.bdf $(FC)
	$(FC) ../bdf/fgs-22.bdf >$@
fixed.snf: ../bdf/fixed.bdf $(FC)
	$(FC) ../bdf/fixed.bdf >$@
fqxb-25.snf: ../bdf/fqxb-25.bdf $(FC)
	$(FC) ../bdf/fqxb-25.bdf >$@
fr-25.snf: ../bdf/fr-25.bdf $(FC)
	$(FC) ../bdf/fr-25.bdf >$@
fr-33.snf: ../bdf/fr-33.bdf $(FC)
	$(FC) ../bdf/fr-33.bdf >$@
fr1-25.snf: ../bdf/fr1-25.bdf $(FC)
	$(FC) ../bdf/fr1-25.bdf >$@
fr2-25.snf: ../bdf/fr2-25.bdf $(FC)
	$(FC) ../bdf/fr2-25.bdf >$@
fr3-25.snf: ../bdf/fr3-25.bdf $(FC)
	$(FC) ../bdf/fr3-25.bdf >$@
frb-32.snf: ../bdf/frb-32.bdf $(FC)
	$(FC) ../bdf/frb-32.bdf >$@
fri-33.snf: ../bdf/fri-33.bdf $(FC)
	$(FC) ../bdf/fri-33.bdf >$@
fri1-25.snf: ../bdf/fri1-25.bdf $(FC)
	$(FC) ../bdf/fri1-25.bdf >$@
ger-s35.snf: ../bdf/ger-s35.bdf $(FC)
	$(FC) ../bdf/ger-s35.bdf >$@
grk-s25.snf: ../bdf/grk-s25.bdf $(FC)
	$(FC) ../bdf/grk-s25.bdf >$@
grk-s30.snf: ../bdf/grk-s30.bdf $(FC)
	$(FC) ../bdf/grk-s30.bdf >$@
hbr-s25.snf: ../bdf/hbr-s25.bdf $(FC)
	$(FC) ../bdf/hbr-s25.bdf >$@
hbr-s40.snf: ../bdf/hbr-s40.bdf $(FC)
	$(FC) ../bdf/hbr-s40.bdf >$@
ipa-s25.snf: ../bdf/ipa-s25.bdf $(FC)
	$(FC) ../bdf/ipa-s25.bdf >$@
krivo.snf: ../bdf/krivo.bdf $(FC)
	$(FC) ../bdf/krivo.bdf >$@
lat-s30.snf: ../bdf/lat-s30.bdf $(FC)
	$(FC) ../bdf/lat-s30.bdf >$@
met25.snf: ../bdf/met25.bdf $(FC)
	$(FC) ../bdf/met25.bdf >$@
micro.snf: ../bdf/micro.bdf $(FC)
	$(FC) ../bdf/micro.bdf >$@
mit.snf: ../bdf/mit.bdf $(FC)
	$(FC) ../bdf/mit.bdf >$@
oldera.snf: ../bdf/oldera.bdf $(FC)
	$(FC) ../bdf/oldera.bdf >$@
plunk.snf: ../bdf/plunk.bdf $(FC)
	$(FC) ../bdf/plunk.bdf >$@
rot-s16.snf: ../bdf/rot-s16.bdf $(FC)
	$(FC) ../bdf/rot-s16.bdf >$@
runlen.snf: ../bdf/runlen.bdf $(FC)
	$(FC) ../bdf/runlen.bdf >$@
sans12.snf: ../bdf/sans12.bdf $(FC)
	$(FC) ../bdf/sans12.bdf >$@
sansb12.snf: ../bdf/sansb12.bdf $(FC)
	$(FC) ../bdf/sansb12.bdf >$@
sansi12.snf: ../bdf/sansi12.bdf $(FC)
	$(FC) ../bdf/sansi12.bdf >$@
serif10.snf: ../bdf/serif10.bdf $(FC)
	$(FC) ../bdf/serif10.bdf >$@
serif12.snf: ../bdf/serif12.bdf $(FC)
	$(FC) ../bdf/serif12.bdf >$@
serifb10.snf: ../bdf/serifb10.bdf $(FC)
	$(FC) ../bdf/serifb10.bdf >$@
serifb12.snf: ../bdf/serifb12.bdf $(FC)
	$(FC) ../bdf/serifb12.bdf >$@
serifi10.snf: ../bdf/serifi10.bdf $(FC)
	$(FC) ../bdf/serifi10.bdf >$@
serifi12.snf: ../bdf/serifi12.bdf $(FC)
	$(FC) ../bdf/serifi12.bdf >$@
stan.snf: ../bdf/stan.bdf $(FC)
	$(FC) ../bdf/stan.bdf >$@
stempl.snf: ../bdf/stempl.bdf $(FC)
	$(FC) ../bdf/stempl.bdf >$@
sub.snf: ../bdf/sub.bdf $(FC)
	$(FC) ../bdf/sub.bdf >$@
subsub.snf: ../bdf/subsub.bdf $(FC)
	$(FC) ../bdf/subsub.bdf >$@
sup.snf: ../bdf/sup.bdf $(FC)
	$(FC) ../bdf/sup.bdf >$@
supsup.snf: ../bdf/supsup.bdf $(FC)
	$(FC) ../bdf/supsup.bdf >$@
swd-s30.snf: ../bdf/swd-s30.bdf $(FC)
	$(FC) ../bdf/swd-s30.bdf >$@
sym-s25.snf: ../bdf/sym-s25.bdf $(FC)
	$(FC) ../bdf/sym-s25.bdf >$@
sym-s53.snf: ../bdf/sym-s53.bdf $(FC)
	$(FC) ../bdf/sym-s53.bdf >$@
variable.snf: ../bdf/variable.bdf $(FC)
	$(FC) ../bdf/variable.bdf >$@
vbee-36.snf: ../bdf/vbee-36.bdf $(FC)
	$(FC) ../bdf/vbee-36.bdf >$@
vctl-25.snf: ../bdf/vctl-25.bdf $(FC)
	$(FC) ../bdf/vctl-25.bdf >$@
vg-13.snf: ../bdf/vg-13.bdf $(FC)
	$(FC) ../bdf/vg-13.bdf >$@
vg-20.snf: ../bdf/vg-20.bdf $(FC)
	$(FC) ../bdf/vg-20.bdf >$@
vg-25.snf: ../bdf/vg-25.bdf $(FC)
	$(FC) ../bdf/vg-25.bdf >$@
vg-31.snf: ../bdf/vg-31.bdf $(FC)
	$(FC) ../bdf/vg-31.bdf >$@
vg-40.snf: ../bdf/vg-40.bdf $(FC)
	$(FC) ../bdf/vg-40.bdf >$@
vgb-25.snf: ../bdf/vgb-25.bdf $(FC)
	$(FC) ../bdf/vgb-25.bdf >$@
vgb-31.snf: ../bdf/vgb-31.bdf $(FC)
	$(FC) ../bdf/vgb-31.bdf >$@
vgbc-25.snf: ../bdf/vgbc-25.bdf $(FC)
	$(FC) ../bdf/vgbc-25.bdf >$@
vgh-25.snf: ../bdf/vgh-25.bdf $(FC)
	$(FC) ../bdf/vgh-25.bdf >$@
vgi-20.snf: ../bdf/vgi-20.bdf $(FC)
	$(FC) ../bdf/vgi-20.bdf >$@
vgi-25.snf: ../bdf/vgi-25.bdf $(FC)
	$(FC) ../bdf/vgi-25.bdf >$@
vgi-31.snf: ../bdf/vgi-31.bdf $(FC)
	$(FC) ../bdf/vgi-31.bdf >$@
vgl-40.snf: ../bdf/vgl-40.bdf $(FC)
	$(FC) ../bdf/vgl-40.bdf >$@
vgvb-31.snf: ../bdf/vgvb-31.bdf $(FC)
	$(FC) ../bdf/vgvb-31.bdf >$@
vmic-25.snf: ../bdf/vmic-25.bdf $(FC)
	$(FC) ../bdf/vmic-25.bdf >$@
vply-36.snf: ../bdf/vply-36.bdf $(FC)
	$(FC) ../bdf/vply-36.bdf >$@
vr-20.snf: ../bdf/vr-20.bdf $(FC)
	$(FC) ../bdf/vr-20.bdf >$@
vr-25.snf: ../bdf/vr-25.bdf $(FC)
	$(FC) ../bdf/vr-25.bdf >$@
vr-27.snf: ../bdf/vr-27.bdf $(FC)
	$(FC) ../bdf/vr-27.bdf >$@
vr-30.snf: ../bdf/vr-30.bdf $(FC)
	$(FC) ../bdf/vr-30.bdf >$@
vr-31.snf: ../bdf/vr-31.bdf $(FC)
	$(FC) ../bdf/vr-31.bdf >$@
vr-40.snf: ../bdf/vr-40.bdf $(FC)
	$(FC) ../bdf/vr-40.bdf >$@
vrb-25.snf: ../bdf/vrb-25.bdf $(FC)
	$(FC) ../bdf/vrb-25.bdf >$@
vrb-30.snf: ../bdf/vrb-30.bdf $(FC)
	$(FC) ../bdf/vrb-30.bdf >$@
vrb-31.snf: ../bdf/vrb-31.bdf $(FC)
	$(FC) ../bdf/vrb-31.bdf >$@
vrb-35.snf: ../bdf/vrb-35.bdf $(FC)
	$(FC) ../bdf/vrb-35.bdf >$@
vrb-37.snf: ../bdf/vrb-37.bdf $(FC)
	$(FC) ../bdf/vrb-37.bdf >$@
vri-25.snf: ../bdf/vri-25.bdf $(FC)
	$(FC) ../bdf/vri-25.bdf >$@
vri-30.snf: ../bdf/vri-30.bdf $(FC)
	$(FC) ../bdf/vri-30.bdf >$@
vri-31.snf: ../bdf/vri-31.bdf $(FC)
	$(FC) ../bdf/vri-31.bdf >$@
vri-40.snf: ../bdf/vri-40.bdf $(FC)
	$(FC) ../bdf/vri-40.bdf >$@
vsg-114.snf: ../bdf/vsg-114.bdf $(FC)
	$(FC) ../bdf/vsg-114.bdf >$@
vsgn-57.snf: ../bdf/vsgn-57.bdf $(FC)
	$(FC) ../bdf/vsgn-57.bdf >$@
vshd-40.snf: ../bdf/vshd-40.bdf $(FC)
	$(FC) ../bdf/vshd-40.bdf >$@
vtbold.snf: ../bdf/vtbold.bdf $(FC)
	$(FC) ../bdf/vtbold.bdf >$@
vtsingle.snf: ../bdf/vtsingle.bdf $(FC)
	$(FC) ../bdf/vtsingle.bdf >$@
vxms-37.snf: ../bdf/vxms-37.bdf $(FC)
	$(FC) ../bdf/vxms-37.bdf >$@
vxms-43.snf: ../bdf/vxms-43.bdf $(FC)
	$(FC) ../bdf/vxms-43.bdf >$@
xif-s25.snf: ../bdf/xif-s25.bdf $(FC)
	$(FC) ../bdf/xif-s25.bdf >$@
