DIRS=common dkmgr tcpmgr svcmgr

all:Q:
	for i in $DIRS
	do	echo ::::$i::::
		(cd $i;mk -p $target)
	done

install:Q:
	for i in $DIRS
	do	echo ::::$i::::
		(cd $i;mk -p $target)
	done

clean:Q:
	for i in $DIRS
	do	echo ::::$i::::
		(cd $i;mk -p $target)
	done

cyntax:Q:
	for i in $DIRS
	do	echo ::::$i::::
		(cd $i;mk -p $target)
	done
