.TH HANG 1
.CT 1 proc_man
.SH NAME
hang \(mi start a process in stopped state
.SH SYNOPSIS
.B hang
.I command
.SH DESCRIPTION
The given command is executed, but stopped before 
.B main()
is called so that
the process can be picked up by a debugger.
.SH SEE ALSO
.IR pi (1), 
.IR kill (1)
.SH BUGS
On the Sun debugged processes still share their text segments.
Thus if multiple instances of an executable are running, it is
impossible to set breakpoints.  A simple fix is to copy the
executable to a new file and debug the new file.
.PP
Attempting to use \fIdbx\fR(1) or \fIdbxtool\fR(1) to attach
to a process started with \fIhang\fR will fail and inhibit all
future debugging on the system until it is rebooted.
