DIRS=libipc libin bin mgrs internet

all:Q:
	for i in $DIRS
	do	echo ::::$i::::
		(cd $i;mk -p $target)
	done

install:Q:
	for i in $DIRS h
	do	echo ::::$i::::
		(cd $i;mk -p $target)
	done

clean:Q:
	for i in $DIRS
	do	echo ::::$i::::
		(cd $i;mk -p $target)
	done

cyntax:Q:
	for i in $DIRS
	do	echo ::::$i::::
		(cd $i;mk -p $target)
	done
